---
language: python
services: docker
dist: xenial
if: tag IS present

python:
  - 3.6

env:
  - ANSIBLE_VERSION=2.8.10
  - ANSIBLE_VERSION=2.9.6

install:
  - pip install docker molecule yamllint ansible-lint ansible==${ANSIBLE_VERSION}

before_script:
  - cd ..
  - mv ansible-role-sonarqube uridium.sonarqube
  - cd uridium.sonarqube

script:
  - molecule test

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_cancel: never
    on_error: never
    on_failure: never
    on_start: never
    on_success: always
  email:
    on_cancel: always
    on_error: always
    on_failure: always
    on_start: never
    on_success: always
