---
- name: Restart SonarQube
  systemd:
    name: sonarqube
    state: restarted
    daemon_reload: yes
  notify: Wait for SonarQube to start

- name: Wait for SonarQube to start
  wait_for:
    port=9000
    delay=5
    sleep=1
    timeout=300
