---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian-systemd-stable
    image: uridium/debian-systemd:stable
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    environment:
      container: docker
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
  flake8
