---
name: test-and-release
on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      max-parallel: 6
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
        ansible-version: [ 2.8.12, 2.9.9 ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Ansible v${{ matrix.ansible-version }}
        run: |
          pip3 install --upgrade \
            pip \
            setuptools
          pip3 install \
            ansible==${{ matrix.ansible-version }} \
            ansible-lint \
            docker \
            flake8 \
            molecule \
            yamllint

      - name: Run Molecule
        env:
          PY_COLORS: True
          ANSIBLE_FORCE_COLOR: True
        run: |
          molecule test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Import role to Galaxy
        run: |
          ansible-galaxy role import --api-key \
            ${{ secrets.galaxy_api_key }} \
            ${GITHUB_REPOSITORY_OWNER} \
            ${GITHUB_REPOSITORY##*/}
